project_id = "rgtiuyrqwrgzqsnkofxy"

[functions.manage-users]
verify_jwt = false

[functions.username-login]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.customer-login]
verify_jwt = false

[functions.order-sms]
verify_jwt = false

[functions.generate-order-number]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.finalize-order]
verify_jwt = false
